// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: internal/proto/form.proto

package formpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FormData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Answer        string                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormData) Reset() {
	*x = FormData{}
	mi := &file_internal_proto_form_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormData) ProtoMessage() {}

func (x *FormData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_form_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormData.ProtoReflect.Descriptor instead.
func (*FormData) Descriptor() ([]byte, []int) {
	return file_internal_proto_form_proto_rawDescGZIP(), []int{0}
}

func (x *FormData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FormData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FormData) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type SubmitReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitReply) Reset() {
	*x = SubmitReply{}
	mi := &file_internal_proto_form_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReply) ProtoMessage() {}

func (x *SubmitReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_form_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReply.ProtoReflect.Descriptor instead.
func (*SubmitReply) Descriptor() ([]byte, []int) {
	return file_internal_proto_form_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_proto_form_proto protoreflect.FileDescriptor

const file_internal_proto_form_proto_rawDesc = "" +
	"\n" +
	"\x19internal/proto/form.proto\x12\x04form\"L\n" +
	"\bFormData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\"'\n" +
	"\vSubmitReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2<\n" +
	"\rFormCollector\x12+\n" +
	"\x06Submit\x12\x0e.form.FormData\x1a\x11.form.SubmitReplyB=Z;github.com/za416854/go-form-collector/internal/proto/formpbb\x06proto3"

var (
	file_internal_proto_form_proto_rawDescOnce sync.Once
	file_internal_proto_form_proto_rawDescData []byte
)

func file_internal_proto_form_proto_rawDescGZIP() []byte {
	file_internal_proto_form_proto_rawDescOnce.Do(func() {
		file_internal_proto_form_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_form_proto_rawDesc), len(file_internal_proto_form_proto_rawDesc)))
	})
	return file_internal_proto_form_proto_rawDescData
}

var file_internal_proto_form_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_form_proto_goTypes = []any{
	(*FormData)(nil),    // 0: form.FormData
	(*SubmitReply)(nil), // 1: form.SubmitReply
}
var file_internal_proto_form_proto_depIdxs = []int32{
	0, // 0: form.FormCollector.Submit:input_type -> form.FormData
	1, // 1: form.FormCollector.Submit:output_type -> form.SubmitReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_form_proto_init() }
func file_internal_proto_form_proto_init() {
	if File_internal_proto_form_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_form_proto_rawDesc), len(file_internal_proto_form_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_form_proto_goTypes,
		DependencyIndexes: file_internal_proto_form_proto_depIdxs,
		MessageInfos:      file_internal_proto_form_proto_msgTypes,
	}.Build()
	File_internal_proto_form_proto = out.File
	file_internal_proto_form_proto_goTypes = nil
	file_internal_proto_form_proto_depIdxs = nil
}
