// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: internal/proto/form.proto

package formpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FormCollector_Submit_FullMethodName = "/form.FormCollector/Submit"
)

// FormCollectorClient is the client API for FormCollector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FormCollectorClient interface {
	Submit(ctx context.Context, in *FormData, opts ...grpc.CallOption) (*SubmitReply, error)
}

type formCollectorClient struct {
	cc grpc.ClientConnInterface
}

func NewFormCollectorClient(cc grpc.ClientConnInterface) FormCollectorClient {
	return &formCollectorClient{cc}
}

func (c *formCollectorClient) Submit(ctx context.Context, in *FormData, opts ...grpc.CallOption) (*SubmitReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitReply)
	err := c.cc.Invoke(ctx, FormCollector_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FormCollectorServer is the server API for FormCollector service.
// All implementations must embed UnimplementedFormCollectorServer
// for forward compatibility.
type FormCollectorServer interface {
	Submit(context.Context, *FormData) (*SubmitReply, error)
	mustEmbedUnimplementedFormCollectorServer()
}

// UnimplementedFormCollectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFormCollectorServer struct{}

func (UnimplementedFormCollectorServer) Submit(context.Context, *FormData) (*SubmitReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedFormCollectorServer) mustEmbedUnimplementedFormCollectorServer() {}
func (UnimplementedFormCollectorServer) testEmbeddedByValue()                       {}

// UnsafeFormCollectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FormCollectorServer will
// result in compilation errors.
type UnsafeFormCollectorServer interface {
	mustEmbedUnimplementedFormCollectorServer()
}

func RegisterFormCollectorServer(s grpc.ServiceRegistrar, srv FormCollectorServer) {
	// If the following call pancis, it indicates UnimplementedFormCollectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FormCollector_ServiceDesc, srv)
}

func _FormCollector_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FormData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormCollectorServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormCollector_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormCollectorServer).Submit(ctx, req.(*FormData))
	}
	return interceptor(ctx, in, info, handler)
}

// FormCollector_ServiceDesc is the grpc.ServiceDesc for FormCollector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FormCollector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "form.FormCollector",
	HandlerType: (*FormCollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _FormCollector_Submit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/form.proto",
}
