global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "go-api"
    static_configs:
      - targets: ["172.17.0.1:8080"]
  - job_name: "go-worker"
    static_configs:
      - targets: ["10.0.1.206:9091"]
